TITLE = "Snake Game"
WIDTH = 1280
HEIGHT = 720
DELAY = 100

BACKGROUND_COLOR = 'yellow'

SNAKE_SHAPE = 'circle'
SNAKE_COLOR = 'green'
SNAKE_SIZE = 20
SNAKE_STARTING_LENGTH = 5

FOOD_SHAPE = 'triangle'
FOOD_COLOR = 'red'
FOOD_SIZE = 20
